### ISSUE TITLE
Server CPU usage - what is normal?

### ISSUE THREAD

**Issue by Fractally** [shaoruu/mine.js#48]
I just had my first look and execution - a very nice project you have here! 😄

I am starting to pick up rust-lang and getting used to actix-web and related infrastructure. I noticed while running the server (without changing any config) on my Windows machine that it was taking close to 30% of my CPU resource after executing main.exe (_yarn server_). My CPU is an i7-8750H.

It seems to be quite a high CPU usage from what I expect to see based on how the world logic works. Could you please give some general indication of the resource usage that you consider normal? My cargo is using the MSVC build tools.

Thanks!

**Comment by shaoruu** [comment]
Thanks for the interest in my project!

I wrote this project last year during quarantine, and back then I also just started learning rust-lang. I got to admit the codebase was very hacky, and I didn't put enough planning into how to structure the project. I got things to work but as the project grew bigger and bigger it got harder and harder to maintain. In terms of the 30% CPU usage, I believe it's most likely due to the world generation on the server, which was very unoptimized.

For the past few months, I have been working on a new project called [`voxelize`](https://github.com/shaoruu/voxelize), which aims to bring the features in MineJS into two fully configurable libraries (client + server). My plan is to rewrite most features in MineJS into voxelize, and eventually use voxelize as the base of MineJS.

Let me know if you have any questions, and welcome to check out my new project!

**Comment by Fractally** [comment]
Thanks for your reply. I always enjoy seeing these passion projects. Will star both and keep an eye.

I noticed you are using JS for the server in voxelize. What general advantages do you expect doing so this time? I assume you can reuse code more and share libs.

Any other general changes you are planning in voxelize as opposed to the current MineJS approach? I see you are sticking to Protocol buffers, but switched to a bit of react rather than svelte on the client.

**Comment by shaoruu** [comment]
I wanted to write voxelize entirely in JS, but as soon as I got to the light calculation and world generation, I realized that no matter how optimized my code was, the speed of JS was no comparison to rust. So, I decided to rewrite (again) the server-side code in rust, and this time, I read up on a lot of idiomatic rust design patterns so I can produce a good-quality voxelize server crate.

In terms of how I plan to implement voxelize, the biggest change I am going to introduce is to start heavily utilizing the ECS (Entity Component System) design pattern, which I believe is very commonly used in game development (Minecraft uses it!) Other than that, I am going to optimize some minor details in the algorithms I implemented, such as coming up with a new implementation for global illumination in the world to get faster and better performance. Also, the code organization should also be improved by a lot in Voxelize (hopefully) 😄

**Comment by Fractally** [comment]
Sounds awesome. I would like to get involved and help you build the new infrastructure in voxelize.

If you want to build a bit more before I get involved that's okay. Otherwise, I can send you a mail and we can discuss what would be useful for me to get going with.

JSYK - I've built a simple voxel engine before so I may quite be useful. 😝

**Comment by shaoruu** [comment]
Sounds awesome! Here's the link to the Trello board I made for Voxelize to keep me organized: [board](https://trello.com/b/SzTDLVm3/voxelize).

Take some time to take a look at what I plan on doing and feel free to shoot me a mail or a PR when you're ready!
